/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI */

#ifndef _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI
#define _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI
 * Method:    createParser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI_createParser
  (JNIEnv *, jobject);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI
 * Method:    parse
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI_parse
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI
 * Method:    getRootNode
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_jni_TreeSitterJNI_getRootNode
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
