/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser */

#ifndef _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser
#define _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser
 * Method:    createParser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser_createParser
  (JNIEnv *, jclass);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser
 * Method:    setParserLanguage
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser_setParserLanguage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser
 * Method:    parse
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser_parse
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser
 * Method:    deleteParser
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_parser_TreeSitterParser_deleteParser
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
