/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree */

#ifndef _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree
#define _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree
 * Method:    deleteTree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree_deleteTree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree
 * Method:    getNodesOfType
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Tree_getNodesOfType
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
