/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node */

#ifndef _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node
#define _Included_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node
 * Method:    freeNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node_freeNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node
 * Method:    getStartByte
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node_getStartByte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node
 * Method:    getEndByte
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node_getEndByte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node
 * Method:    getNodeCoordinates
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_beatrice_rag_repositoryprocessor_textchunker_treesitter_java_wrappers_Node_getNodeCoordinates
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
